services:
  api:
    build: .
    ports: ["5000:5000"]
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    command: python api/app.py

  ui:
    build: .
    ports: ["8501:8501"]
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    command: streamlit run app_streamlit.py --server.port=8501 --server.address=0.0.0.0
    depends_on: ["api"]